# Generated by Django 3.1 on 2020-09-17 21:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_complex', models.IntegerField()),
                ('unit_number', models.IntegerField()),
                ('sub_complex', models.IntegerField()),
                ('street_number', models.IntegerField()),
                ('street_name', models.CharField(max_length=255)),
                ('neighbourhood', models.CharField(max_length=255)),
                ('suburb', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=255)),
                ('postal_code', models.IntegerField()),
                ('country', models.IntegerField(max_length=255)),
                ('GPS_coordinates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployerTable',
            fields=[
                ('employer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employer_name', models.CharField(max_length=255)),
            ],
        ),
    ]
