# Generated by Django 3.1 on 2020-09-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresstable',
            name='country',
            field=models.CharField(max_length=255),
        ),
    ]
