# Generated by Django 3.1 on 2020-09-17 21:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employer', '0001_initial'),
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTable',
            fields=[
                ('job_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('job_title', models.CharField(db_index=True, max_length=255)),
                ('job_description', models.TextField()),
                ('applicant_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Rather not say')], default='N/A', max_length=50)),
                ('job_open_for_application', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=50)),
                ('job_filled', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='Y', max_length=50)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.addresstable')),
                ('employer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employer.employertable')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('application_letter', models.TextField()),
                ('application_submitted', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=50)),
                ('application_status', models.CharField(choices=[('OP', 'Open'), ('UR', 'Under review'), ('R', 'Reviewed'), ('IS', 'Interview scheduled'), ('C', 'Closed')], default='Y', max_length=50)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.jobtable')),
                ('job_seeker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_seeker.jobseekertable')),
            ],
        ),
    ]
